name: confluence-cli
version: 0.1.0
synopsis: Command line interface for Atlassian Confluence.
category: CLI
description: Please see the README on GitHub at <https://github.com/farbodsz/confluence-cli#readme>
github: "farbodsz/confluence-cli"
license: MIT
author: "Farbod Salamat-Zadeh"
copyright: "2022 Farbod Salamat-Zadeh"
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - directory
  - extra
  - filepath
  - http-client
  - http-conduit
  - http-types
  - mtl
  - optparse-applicative
  - text

default-extensions:
  - DeriveGeneric
  - DuplicateRecordFields
  - ImportQualifiedPost
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  confluence:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - confluence-cli
